### ISSUE TITLE
Update versions, or tag with 'latest'?

### ISSUE THREAD

**Issue by Jaykul** [OctopusDeploy/Octopus-Docker#1]
Since you are not updating these docker images with every Octopus release, and you have a `--BuildArgs` option to pass in the version, it seems to me that you should stop using the `OctopusVersion` parameter to your scripts as the version for the docker image.  Tag each new release with `latest` and use that tag in your scripts.  

It would be fine if we could `docker build` and pass the `OctopusVersion` as a `--build-arg` ... but it seems there are a few pieces missing: /Source?

Unless, of course, the intention is for this to look old and stale?

**Comment by matt-richardson** [comment]
As mentioned in #2, this is a preview only, and we do not consider it stable as yet.

The build server downloads the appropriate msi and drops it into the source folder. I believe that there was code there that checked to make sure it existed, and if not, downloaded it, but I think it got dropped in a cleanup.

I see you've logged a PR #4 - we'll look into that and continue the conversation over there.
