### ISSUE TITLE
Octopus Tentacle with private IP

### ISSUE THREAD

**Issue by rajpolaris** [OctopusDeploy/Octopus-Docker#10]
I have Octopus server running in a VNET in Azure.
I added a new Windows Server 2016 with containers in the same subnet.

I tried to run standalone docker container on win 2016 VM using this command

docker run --publish 10931:10933 --tty --interactive --env "ListeningPort=10931" --env "ServerApiKey=xxxxxx" --env "TargetEnvironment=Test" --env "TargetRole=app-server" --env "ServerUrl=https://my.octoserver.com"  --env "PublicHostNameConfiguration=PublicIp" octopusdeploy/tentacle:3.15.8

I did not want to use publicIp so first I tried PublicHostNameConfiguration=ComputerName

Container started successfully but it looked unhealthy to the OctopusServer.
When I tried to check the health Octopus server was using incorrect name for the VM that was hosting Tentancle running in Docker. Perhaps it used Container Name instead of the VM name so it had no way to reach the VM hosting the Docker container.

Next I tried passing in 

--env "PublicHostNameConfiguration=Custom" --env "CustomPublicHostName=10.0.0.37"

docker container failed to start. It failed in Tentacle register-with step.

Unrecognized command line arguments: https://my.octoserver.com

Can you tell me how I can run Octopus Tentacle in a docker container when the VM only has private IP?

**Comment by matt-richardson** [comment]
It appears we don't support `PublicHostNameConfiguration=Custom` very well. It looks like when we [get the public host name](https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Tentacle/Scripts/configure-tentacle.ps1#L153) we don't actually pass anything for the second argument `$customPublicHostName`, and therefore when its executing the 'register-with' command it passes a blank value for `--publicHostName`.

Unfortunately we're not in a place where we can tackle this right now, but if you are willing to implement, test and raise a PR, we'd be more than happy to accept it.

I suspect if you removed the `$customPublicHostName` [parameter](https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Tentacle/Scripts/configure-tentacle.ps1#L82) and returned `$env:CustomPublicHostName` [here](https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Tentacle/Scripts/configure-tentacle.ps1#L86), that'd be about all it'd need.

**Comment by matt-richardson** [comment]
This has now been published in the `3.17.0` Tentacle container.
