### ISSUE TITLE
Cannot access Octopus Server form external host

### ISSUE THREAD

**Issue by nmajin** [OctopusDeploy/Octopus-Docker#16]
I am running Octopus Deploy server in a container on Windows Server 2016 and I cannot get access to the container/console on an external host. I know Windows Containers has some issues with NAT'ing, but I was hoping if there is some documentation you can provide to figure out how to accomplish this.

I tried the following [doc](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/), but no luck; docker doesn't seem to provide IPs to the containers, so technically it doesn't. seem like I set this up correctly.

**Comment by cvandal** [comment]
Hey @nmajin!

Sounds to me as though you haven't mapped your ports correctly or you haven't opened your firewall for your port.

As you mentioned, there are differences with Docker on Windows when it comes to networking; we don't have the bridge adapter, we have the NAT adapter (for now at least, an insiders build of Windows removes this limitation). This means you can only access the containers via the host IP address.

Here's some official doco on Docker networking: https://docs.docker.com/config/containers/container-networking
Here's some Microsoft doco on Docker networking for Windows: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking

Ensure that you're exposing port 80 in your Dockerfile and that you're mapping port 80 on the host to port 80 on the container.

**Comment by nmajin** [comment]
Thanks for the reply. Let me see if I can clarify. So I am using your docker-compose file: https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Server/docker-compose.yml, which seems to work fine based on looking at the container logs and running a simple curl command to hit the portal on the Windows host running the containers, referencing the container IP. In your compose file you have port 81 exposed and forwarded to the host. I have port 81 allowed and enabled on the Windows host firewall, but I still cannot access the portal externall by hitting http://<windows host ip>:81.

**Comment by cvandal** [comment]
Can you run `docker ps -a` and provide the output?

**Comment by nmajin** [comment]
Oh wow, I cannot believe I confused the ports and didn't even try to access `http://<host_ip>:23278` I just tried externally from the host and I can access the sign in page. Thanks for the help!

**Comment by cvandal** [comment]
No worries!
