### ISSUE TITLE
PowerShell scripts referencing non-existent tag?

### ISSUE THREAD

**Issue by Jaykul** [OctopusDeploy/Octopus-Docker#2]
All the PowerShell scripts are using:

```posh
docker build --tag octopusdeploy/octopusdeploy-prerelease:$OctopusVersion
```

When it should be `octopusdeploy/octopusdeploy:$OctopusVersion`

It might also be worth setting a default version for the PowerShell scripts. The cmd file has this:

```cmd
if "%OctopusVersion%" equ "" (
	set OctopusVersion=3.7.10
	echo No OctopusVersion environment variable set. Defaulting to %OctopusVersion%.
)
```

The PowerShell one should have it too

```posh
param (
  [Parameter(Mandatory=$true)]
  [string]$OctopusVersion = "3.7.10"
)
```

Or, you know, update the version to the latest, and tag it as in #1 ...

**Comment by matt-richardson** [comment]
Thanks for getting in touch. At the moment, this repo is still a preview and is unsupported. Unfortunately, Docker on Windows is not particularly stable, so it hasn't been a priority for us. That said, we are hoping the situation will improve soon.

The `octopusdeploy/octopusdeploy-prerelease ` repo is a private docker repo, so it is correct. Once Octopus-in-a-Docker-container comes out of preview and we're confident it wont cause a large increase in support issues, we'll start publishing to the main `octopusdeploy/octopusdeploy` repo.

The version values are passed in via the build server - the defaults are just there to make life a bit easier during dev.
