### ISSUE TITLE
Tag new release of 2018.8

### ISSUE THREAD

**Issue by sylus** [OctopusDeploy/Octopus-Docker#29]
Hi there!

I was wondering if we could trigger a new build for 2018.8 so that it contains the #28 fix?

Thanks so much!

**Comment by sylus** [comment]
@zentron

**Comment by zentron** [comment]
I've re-pushed `2018.8.8` however dockerhub appears to be having problems and not updating so keep an eye on https://hub.docker.com/r/octopusdeploy/octopusdeploy/tags/
`2018.8.9` should be going out in the next few days as well if that cache doesn't update :)

**Comment by sylus** [comment]
Thanks so much @zentron your amazing :)
