### ISSUE TITLE
Please provide Compose.yml

### ISSUE THREAD

**Issue by Jaykul** [OctopusDeploy/Octopus-Docker#3]
Rather than a PowerShell script to kick off the multiple docker images, you should be using `compose` now that it's working on Windows...

**Comment by zentron** [comment]
Hi @Jaykul , great to see you are taking a look into this project. At the moment we have still seen issues with docker-compose on windows so while we are continuing to keep an eye on it, for the time being its not a priority. 
Its certainly something we want to provide (and were just talking about this yesterday!)
