### ISSUE TITLE
Volume mount with C:/octopus fails w/Docker 2018.8+

### ISSUE THREAD

**Issue by sylus** [OctopusDeploy/Octopus-Docker#32]
Hey amazing Octopus folks, I am using Octopus largely without issue and with Azure AD etc. However whenever our K8S node restarts it seems Octopus no longer works. I noticed this is because I am not mounting the c:/octopus directory as a volume mount

However when I do that in versions later then 2018.8+ I get the below message:

**Comment by zentron** [comment]
That is odd we are definately retrieving the master key https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Server/Scripts/configure.ps1#L10 and this is used in the build tests for this container

If you run it without k8s, just through standard docker run steps does it still not pick it up? What do your logs look like?

**Comment by zentron** [comment]
I can see that it is finding the master key in the environment variables (hence the `-masterKey '###'` log line). Based on the error message there I would say its because you are trying to pass in the username and password again to that installation. Although the error message says `To change the administrator passwords login details for an existing installation, run this image passing in arguments for the admin command` this is actually not currently supported (ill update the error message accordingly)
Try run your second server instance without passing in the username\password

**Comment by sylus** [comment]
Yeah i noticed I don't need the masterKey as long as I volume mount the C:\Octopus folder it will persist on restarts, however this only works on 2018.6-1803 as all newer versions complain of the octopus.server.config file not initially existing.

**Comment by FrancisGrignon** [comment]
I have the same issue using a docker-compose using octopusdeploy/octopusdeploy:2018.8.12. The image octopusdeploy/octopusdeploy:2018.8.6 is fine.

**Comment by sylus** [comment]
@zentron I updated the description of the issue, I can try to find where this broke in the scripts but might take me a day or two.

**Comment by zentron** [comment]
👍 
I think this might be another case of `C:\Octopus` not being expected to be mounted so falling through the cracks. we are accounting for\testing the other standard directories (packages\artifacts\task logs) but perhaps need to cover the home directory.
what contents specifically of `C:\Octopus` are you looking to mount externally? Im guessing its mainly just the server logs?

**Comment by sylus** [comment]
@zentron for me I just need the C:\Octopus\OctopusServer.config file to persist on restart which was why added the volume mount. ^_^

**Comment by zentron** [comment]
BY restart do you mean `docker start` -> `docker stop` or spinning up a new instance?

**Comment by sylus** [comment]
Hey @zentron I just mean docker stop -> start, technically in k8s just the node coming down for the night. Technically on 2018.8 + the default docker-compose file also doesn't work.

https://octopus.com/blog/docker-compose

**Comment by sylus** [comment]
Let me know how I can help. I know we (Statistics Canada) are actively evaluating this, but this is def a pain point for us preventing review.

**Comment by sylus** [comment]
Ah okay I figured this out as the mapping has changed from the docs on the docker-compose file structure but work fine with the defaults set in server folder.

Updated the chart to support the same mappings and to not set the environment variables for admin + pass if master key is given, and it seems to work.

Thanks a bunch :)
