### ISSUE TITLE
1809 support

### ISSUE THREAD

**Issue by christianacca** [OctopusDeploy/Octopus-Docker#40]
Do you have an eta when you're going to start pushing an 1809 image to docker hub?

Thanks
Christian

**Comment by matt-richardson** [comment]
We're looking at it, but its not as simple as you'd like. We've got the infrastructure setup (ie, a Win1809 build agent) so we can build it, so its just updating the builds now. Doesn't help that Microsoft has moved things around and no longer stores images on dockerhub 🤦‍♂️.

Hopefully "soon".

**Comment by christianacca** [comment]
Ok great. I'll watch out for the update

**Comment by christianacca** [comment]
Noticed that you guys use my mssql-server-windows-express docker image: https://github.com/OctopusDeploy/Octopus-Docker/blob/master/Server/02-start.ps1#L20

That image repository also supports 1809. In fact it's a multi-architecture image which means if you drop the 1803/1809 tag, docker will pull the correct image for the target platform your octopus build is running on.

So I would suggest updating your build script to use: `christianacca/mssql-server-windows-express:2017-latest`

**Comment by christianacca** [comment]
If you need that `christianacca/mssql-server-windows-express` image to be updated let me know.

**Comment by christianacca** [comment]
`christianacca/mssql-server-windows-express` supports Windows 1809 which IS Windows 2019 isn't it?

**Comment by matt-richardson** [comment]
Not that I'm aware of? 

For our build agents, for 1809, we're using `Windows_Server-1809-English-Core-Containers`. For 2019, we're using `Windows_Server-2019-English-Full`. So, AWS at least thinks its a different OS?

**Comment by matt-richardson** [comment]
Seems they are very similar but different:

> The difference between Windows Server 2019 and Windows Server, version 1809 is mainly how updates will be released. If you're on the Long-Term Servicing Channel, you're going to receive cumulative updates, similar to how Windows Server 2016 has (Windows Server 2016 coincided with version 1607). Those on the Semi-Annual Channel will get the next feature update, which will likely be version 1903.

 - https://www.neowin.net/news/windows-server-2019-and-windows-server-version-1809-will-be-generally-available-in-october/

**Comment by christianacca** [comment]
Yeah, I know the updates for the OS are released differently, but in terms of the windows kernel it's the same.

Here's my understanding of the situation...

I think the issue that you getting at is what base image will the consumer get when they issue the command: `docker pull christianacca/mssql-server-windows-express`

The result would be the _same_ regardless of whether that command was issued from a windows server 2019 or a windows server lts-2019.

However, the author (me) of `christianacca/mssql-server-windows-express` has made the choice for the consumer - they are going to get an image based on `mcr.microsoft.com/windows/servercore:1809` _or_ one based on `mcr.microsoft.com/windows/servercore:ltsc2019` - which one depends on the one I specified when defining the docker file for `christianacca/mssql-server-windows-express`

**Comment by matt-richardson** [comment]
In that case, I think we're good :)

Looks like we've had a few 1809 images published over the last few days, so you should be good to go.

**Comment by christianacca** [comment]
Great. I'm going to take for a spin over the weekend
