### ISSUE TITLE
Tentacle for 1809

### ISSUE THREAD

**Issue by christianacca** [OctopusDeploy/Octopus-Docker#43]
Can you push an 1809 version of the tentacle? It would be good if it was the latest version of the calamari (4.13.1).

Thanks
Christian

**Comment by christianacca** [comment]
(bump)

I'm assuming that you guys are planning to keep the tentacle image up to date?

**Comment by christianacca** [comment]
(bump)

**Comment by matt-richardson** [comment]
Hey @christianacca - sorry about the delay there. We'd actually started building and publishing these a while ago, but forgot the "move the images from the private to public repo" part. I've just pushed out the 1809 version now. Hope that helps!

**Comment by christianacca** [comment]
It certainly does :-)
