### ISSUE TITLE
Question: Upgrading the server

### ISSUE THREAD

**Issue by Kemyke** [OctopusDeploy/Octopus-Docker#8]
Can you help me please, what is the recommended way of upgrading an existing Octopus deploy server which is running in container?
Is it enough to replace the server container if all the configs and assets are stored on volume? 
It would be greate to have a paragraph on this in the readme!

**Comment by cvandal** [comment]
Hey @Kemyke!

Thanks for reaching out! Glad to hear that you're using Octopus in a docker container and it's working well for you.

I am going to do some local testing to confirm this, but I believe that so long as your DB is external, or your DB files are stored on a separate volume, and your config is also on a separate volume, you should be fine with simply replacing the server container. When the container launches, it will automatically update the DB and config files for you. Just make sure that when you launch your new server container that you pass in your existing master key as an environment variable.

I'll get back to you with my results asap.

**Comment by cvandal** [comment]
Hey @Kemyke, I've finished my testing. I successfully upgraded from 4.1.3 to 4.1.4 by simply stopping my docker container running Octopus Server 4.1.3, adding `MASTERKEY=xyz` to my `.env` file, and then starting a new docker container running Octopus Server 4.1.4. I was also using an external DB, and all of my config was stored on a volume.

**Comment by Kemyke** [comment]
Yeah, actually we migrated to the container version of Octopus Server just few days ago, and it is working well so far. :)
Thanks, for the help!

**Comment by cvandal** [comment]
Awesome! Happy to hear it. We'll definitely add some additional doco around upgrading an Octopus Server in the container world in the near future as we flesh out processes and scenarios.
